"""creative_worker.py - Director Creativo: After Effects + Remotion + FFmpeg.

Estrategia hibrida:
  1. PRIMERA OPCION: codigo (Remotion + FFmpeg) - 100% determinista, sin GUI
  2. PREMIUM: After Effects ExtendScript - modifica plantillas .aep
     programaticamente, abre AE via CLI, dispara render desde script o GUI
  3. FALLBACK: GUI via SoM - solo si AE no acepta CLI

After Effects CLI:
  afterfx.exe -r "C:\path\to\script.jsx"
  afterfx.exe -m -r script.jsx  (modo headless si disponible)

Templates location: data/ae_templates/ (proyectos .aep + scripts .jsx asociados)
Output: data/ae_renders/<timestamp>/
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

TEMPLATES_DIR = ROOT / "data" / "ae_templates"
RENDERS_DIR = ROOT / "data" / "ae_renders"

# Buscar After Effects en ubicaciones estandar
AE_PATHS = [
    r"C:\Program Files\Adobe\Adobe After Effects 2025\Support Files\AfterFX.exe",
    r"C:\Program Files\Adobe\Adobe After Effects 2024\Support Files\AfterFX.exe",
    r"C:\Program Files\Adobe\Adobe After Effects 2023\Support Files\AfterFX.exe",
    r"C:\Program Files\Adobe\Adobe After Effects (Beta)\Support Files\AfterFX.exe",
]


def find_after_effects() -> str | None:
    for p in AE_PATHS:
        if Path(p).exists():
            return p
    return None


def generate_extendscript(template_aep: str, output_path: str,
                           variables: dict) -> str:
    """Genera codigo ExtendScript que abre plantilla, inyecta vars y exporta.

    Args:
        template_aep: path absoluto al .aep
        output_path: donde guardar el video final (.mp4 o .mov)
        variables: dict {layer_name: new_value} para reemplazar text layers

    Returns:
        codigo .jsx como string
    """
    # ExtendScript (JS variante de Adobe). Notar escaping windows paths.
    aep_path_js = template_aep.replace("\\", "\\\\")
    out_path_js = output_path.replace("\\", "\\\\")
    var_assignments = []
    for layer_name, value in variables.items():
        # Escape quotes/special chars in value
        clean_value = (str(value)
                       .replace("\\", "\\\\")
                       .replace('"', '\\"'))
        var_assignments.append(
            f'  setTextLayer("{layer_name}", "{clean_value}");'
        )
    var_block = "\n".join(var_assignments) if var_assignments else "  // no vars"

    return f"""// Auto-generated by Jarvis v2 creative_worker
// Generated: {datetime.utcnow().isoformat()}

function setTextLayer(layerName, newText) {{
  var proj = app.project;
  for (var i = 1; i <= proj.numItems; i++) {{
    var item = proj.item(i);
    if (item instanceof CompItem) {{
      for (var j = 1; j <= item.numLayers; j++) {{
        var layer = item.layer(j);
        if (layer.name === layerName && layer.property("Source Text")) {{
          layer.property("Source Text").setValue(newText);
        }}
      }}
    }}
  }}
}}

function main() {{
  app.openFast = true;
  var aepFile = new File("{aep_path_js}");
  app.open(aepFile);

  app.beginUndoGroup("Jarvis Auto Edit");
{var_block}
  app.endUndoGroup();

  // Render queue add the main comp (asumiendo nombre 'Main')
  var mainComp = null;
  for (var i = 1; i <= app.project.numItems; i++) {{
    if (app.project.item(i) instanceof CompItem &&
        app.project.item(i).name === "Main") {{
      mainComp = app.project.item(i);
      break;
    }}
  }}
  if (mainComp) {{
    var rqItem = app.project.renderQueue.items.add(mainComp);
    var outModule = rqItem.outputModule(1);
    outModule.file = new File("{out_path_js}");
    app.project.renderQueue.render();
  }}
  app.project.save();
}}

main();
"""


def render_via_extendscript(template_aep: str, variables: dict,
                             output_name: str = "output.mp4",
                             ae_exe: str | None = None,
                             timeout: int = 1800) -> dict:
    """Renderiza via AE CLI + ExtendScript."""
    ae_exe = ae_exe or find_after_effects()
    if not ae_exe:
        return {"ok": False, "error": "after_effects_not_found",
                "checked": AE_PATHS}

    RENDERS_DIR.mkdir(parents=True, exist_ok=True)
    run_dir = RENDERS_DIR / datetime.utcnow().strftime("%Y%m%d_%H%M%S")
    run_dir.mkdir(parents=True, exist_ok=True)
    output_path = str(run_dir / output_name)
    script_path = run_dir / "auto.jsx"

    jsx_code = generate_extendscript(template_aep, output_path, variables)
    script_path.write_text(jsx_code, encoding="utf-8")
    print(f"[creative] script: {script_path}", flush=True)

    t0 = time.time()
    try:
        r = subprocess.run(
            [ae_exe, "-r", str(script_path)],
            capture_output=True, text=True, timeout=timeout,
        )
        elapsed = time.time() - t0
        ok = r.returncode == 0 and Path(output_path).exists()
        return {
            "ok": ok,
            "output_file": output_path if ok else None,
            "duration_s": elapsed,
            "stderr": (r.stderr or "")[-500:],
            "stdout": (r.stdout or "")[-500:],
            "ae_exe": ae_exe,
            "script_path": str(script_path),
        }
    except subprocess.TimeoutExpired:
        return {"ok": False, "error": "ae_timeout", "duration_s": timeout}
    except Exception as e:
        return {"ok": False, "error": str(e)}


def render_via_remotion(project_dir: str, composition_id: str,
                         output_name: str, props: dict | None = None) -> dict:
    """Fallback: Remotion (TypeScript) render."""
    try:
        from jarvis_v2.skills.ffmpeg_video import render_remotion
        RENDERS_DIR.mkdir(parents=True, exist_ok=True)
        out = str(RENDERS_DIR / output_name)
        return render_remotion(project_dir, composition_id, out, props)
    except Exception as e:
        return {"ok": False, "error": str(e)}


def render_from_template(order: dict) -> dict:
    """Entry point del orchestrator. Order schema:
    {
      "department": "creative",
      "objective": "Crear anuncio TikTok para producto X",
      "template_type": "ae|remotion",
      "template": "ad_template.aep" or "remotion_project_path",
      "variables": {"title": "...", "subtitle": "..."},
      "composition_id": "MainAd"  (solo Remotion)
    }
    """
    print(f"[creative] order: {order.get('objective', '')[:80]}", flush=True)
    ttype = order.get("template_type", "ae")

    if ttype == "ae":
        template_aep = order.get("template", "")
        if not template_aep or not Path(template_aep).exists():
            # Buscar en templates dir
            t = TEMPLATES_DIR / template_aep
            if t.exists():
                template_aep = str(t)
            else:
                return {"ok": False, "error": f"template_not_found: {template_aep}"}
        return render_via_extendscript(
            template_aep=template_aep,
            variables=order.get("variables", {}),
            output_name=order.get("output_name", "out.mp4"),
        )
    elif ttype == "remotion":
        return render_via_remotion(
            project_dir=order["template"],
            composition_id=order.get("composition_id", "Main"),
            output_name=order.get("output_name", "out.mp4"),
            props=order.get("variables", {}),
        )
    else:
        return {"ok": False, "error": f"unknown_template_type: {ttype}"}


if __name__ == "__main__":
    # Smoke test (sin renderizar, solo verifica que detecta AE y genera script)
    ae = find_after_effects()
    print(f"After Effects detected: {ae}")
    if ae:
        # Genera un script de prueba
        sample_aep = TEMPLATES_DIR / "sample.aep"
        TEMPLATES_DIR.mkdir(parents=True, exist_ok=True)
        script = generate_extendscript(
            str(sample_aep), "C:/tmp/out.mp4",
            {"TitleText": "Hola mundo", "SubtitleText": "Generated by Jarvis"},
        )
        print(f"\n=== Generated jsx preview (head) ===\n{script[:600]}...")
    else:
        print("After Effects no instalado. Solo Remotion/FFmpeg disponible.")
